# NumPy (Numeric Python)

In [2]:
a = [1, 2, 3, 4]
b = [5, 6 ,7, 8]
c = a + b
print(c)

[1, 2, 3, 4, 5, 6, 7, 8]


In [3]:
print(type(a))
print(type(b))

<class 'list'>
<class 'list'>


In [4]:
import numpy as np

In [5]:
# NumPy Array
# np.array() -> List -> Convert to Numpy Array
a_array = np.array(a)
b_array = np.array(b)
c_array = a_array + b_array
c_array

array([ 6,  8, 10, 12])

In [6]:
# 1D List and 2/Multi D List
# 1D Array and 2/Multi D Array
multi_array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
multi_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
a_array.shape

(4,)

In [8]:
print(multi_array.shape)
print(multi_array.size)

(3, 4)
12


In [9]:
# to get total number of record in an array
multi_array.size

12

In [10]:
# ndim -> show dimension of an array
print(a_array.ndim)
print(multi_array.ndim)

1
2


# Zeros and Ones

In [11]:
# zeros(shape, dtype=int/float) -> default value -> float
zero_1d = np.zeros(5, dtype=int)
zero_1d

array([0, 0, 0, 0, 0])

In [12]:
one_1d = np.ones(5, dtype=int)
one_1d

array([1, 1, 1, 1, 1])

In [13]:
zero_2d = np.zeros((3, 4), dtype=int)
print(zero_2d)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [14]:
ones_2d = np.ones((3, 4), dtype=int)
ones_2d

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

# Reshape and Ravel

In [15]:
ones_2d

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [16]:
reshape_oned = ones_2d.reshape(2, 6)
reshape_oned

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [17]:
ravel_shape = reshape_oned.ravel()
ravel_shape

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# arange

In [18]:
numbers = np.arange(1, 61)
numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

In [19]:
res_num = numbers.reshape(6, 10)
res_num

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

# Array Broadcasting

In [20]:
'''
Rules of Broadcasting
-----------------------
1. All dimesion of array shape must be equal.
2. Any shape of array must be 1 and other must be equal.
3. If one shape of array is 1 X 1 then it does calculates with any shape of array.
'''

'\nRules of Broadcasting\n-----------------------\n1. All dimesion of array shape must be equal.\n2. Any shape of array must be 1 and other must be equal.\n3. If one shape of array is 1 X 1 then it does calculates with any shape of array.\n'

In [21]:
multi_arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
]) # 3 X 4

multi_arr2 = np.array([
    [13]
]) # 1 X 1

In [22]:
add = multi_arr + multi_arr2
print(add)

[[14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]


# Boolean Indexing

In [23]:
filter_numbers = numbers > 50
filter_numbers

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [24]:
numbers[filter_numbers]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60])

In [25]:
fruits = np.array(["Apple", "Apple", "Apple", "Banana", "Orange", "Mango"])
filter_fruits = fruits == "Apple"
filter_fruits

array([ True,  True,  True, False, False, False])

In [26]:
fruits[filter_fruits]

array(['Apple', 'Apple', 'Apple'], dtype='<U6')